---
default:
  image: ghcr.io/stefan-hoeck/idris2-pack:latest
  interruptible: true
  before_script:
    - find . -name '.pack.*.tar' -exec tar -xf '{}' --one-top-level=/ --touch \;
  after_script:
    - rm -f .pack.*.tar
    - |
      if [[ "$CI_JOB_NAME" =~ ":build" || "$CI_JOB_NAME" =~ "pack:" ]]
        then tar -cf "$CI_PROJECT_DIR/.pack.${CI_JOB_NAME/:/-}.tar" --exclude=".cache" "$PACK_DIR"
      fi
  artifacts:
    paths:
      - "**/build/**/*.tt[cm]"
      - ".pack.*.tar"
    expire_in: 3 hrs

pack:prepare:
  stage: .pre
  script:
    - pack update-db
    - pack switch "$( if [[ "$CI_PIPELINE_SOURCE" == 'schedule' ]]; then echo HEAD; else ./.pack-collection; fi )"

stages:
  - deptycheck:build
  - examples
  - deptycheck:test

thirdparties:build:
  stage: deptycheck:build
  needs:
    - pack:prepare
  script:
    - pack install-deps deptycheck
    - pack install summary-stat # for distr tests
      # TODO to compute test dependencies when we have special mini-test libs

deptycheck:build:
  stage: deptycheck:build
  needs:
    - thirdparties:build
  script:
    - pack build deptycheck
    - pack install deptycheck

deptycheck:test:
  stage: deptycheck:test
  needs:
    - deptycheck:build
  parallel:
    matrix:
      - TEST_SET: [ TEST_SETS ]
  script:
    - pack test deptycheck "$TEST_SET"

example:build-and-test:
  stage: examples
  needs:
    - deptycheck:build
  parallel:
    matrix:
      - EXAMPLE: [ EXAMPLES_SET ]
  script:
    - pack build "$EXAMPLE"
    - pack test "$EXAMPLE"
